name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v1
      - name: sonarCloudScan
        uses: sonarsource/sonarcloud-github-action@master
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}          
          
      - name: SonarCloudResult
        run: |
            BT_STATUS=$(curl -s https://status.bintray.com/api/v2/status.json |  jq --raw-output '.status.description')
            echo “Bintray API Status: $BT_STATUS”
            if [ “$BT_STATUS” != “All Systems Operational” ]; then
            echo “Error [Bintray API Status: $BT_STATUS]”
             exit 1
            fi     
      
