name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v1
      - name: sonarCloudScan
        uses: sonarsource/sonarcloud-github-action@master
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}          
          
      - name: SonarCloudResult   
        run: | 
            BT_STATUS=$(curl -iL --max-redirs 1 "http://sonarcloud.io/api/qualitygates/project_status?projectKey=bcbrunocesar_react-hooks-ts")
            echo "SonarCloud API: $BT_STATUS"
            if [ "$BT_STATUS" != "OK" ]; then
              echo "Error [SonarCloud API Status: $BT_STATUS]"
              exit 1
            fi 
     
      
