name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v1
      - name: sonarCloudScan
        uses: sonarsource/sonarcloud-github-action@master
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}          
          
      - name: Echo the greeting's time
        run: echo 'The time was ${{ http://sonarcloud.io/api/qualitygates/project_status?projectKey=bcbrunocesar_react-hooks-ts }}.'       
      
